"""telegram link codes

Revision ID: 1b15848deb18
Revises: 19a1cbf92da7
Create Date: 2026-06-02 11:53:37.141162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b15848deb18'
down_revision: Union[str, None] = '19a1cbf92da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_link_codes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_link_codes_code'), 'telegram_link_codes', ['code'], unique=True)
    op.create_index(op.f('ix_telegram_link_codes_user_id'), 'telegram_link_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_link_codes_user_id'), table_name='telegram_link_codes')
    op.drop_index(op.f('ix_telegram_link_codes_code'), table_name='telegram_link_codes')
    op.drop_table('telegram_link_codes')
    # ### end Alembic commands ###
